### ISSUE TITLE
Release MP 7.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-marketing#945]
- [x] MicroProfile 7.0 Specification Review [git issue](https://github.com/microprofile/microprofile-wg/issues/244). 
- [x] If this release is the first release for this year, create a release folder (xxxx Release, e.g 2023 Release) under this [root folder](https://drive.google.com/drive/u/0/folders/1LgxGyXwOjpJMkWBZZ5eVm8JpfLA7heS4). This folder stores the releases blog and release presentation to be created in the next few steps. (@jclingan) <br/> 
- [x] Create a [MicroProfile presentation](https://docs.google.com/presentation/d/1gg67Gv38B8QJ9o0u_pwoiQf3NvigB_MgL7ZgabL_I2U/edit#slide=id.p1) and save it in the right folder under this (@jclingan) [Ticket](https://github.com/eclipse/microprofile-marketing/issues/961) [example here](https://github.com/eclipse/microprofile-marketing/issues/836) <br/>
- [ ] Import the presentation to the landing page and resources page of the website<br/>
- [x] Draft a release announcement blog post using template (@Emily-Jiang ) [Ticket](https://github.com/eclipse/microprofile-marketing/issues/962) [example here](https://github.com/eclipse/microprofile-marketing/issues/548)<br/>
- [x] Create a compatible implementation page for this release and list the compatible implementation used for this release ratification [ticket](https://github.com/eclipse/microprofile-marketing/issues/963) [example here](https://github.com/eclipse/microprofile-marketing/issues/548)<br/>
- [x] Create release announcement design card [ticket](https://github.com/eclipse/microprofile-marketing/issues/964) ----- [See example here](https://github.com/eclipse/microprofile-marketing/issues/546) <br/>
- [x] Update the MicroProfile homepage with release announcement design card<br/>
- [x] Edit/Publish release announcement blog post on the MicroProfile Blog [Ticket](https://github.com/eclipse/microprofile-marketing/issues/962) <br/>
- [x] Announce release on social media using Hootsuite (Twitter, Linkedin, Facebook) [example here](https://github.com/eclipse/microprofile-marketing/issues/542)<br/>
- [x] Write an update to the MP Community Forum about the release (@jclingan volunteered)<br/>
- [x] Update the MP Calendar with the Release Date (committer)
- [ ] Translate the release blog in other lauguages such as (German,Russian, Spanish, etc)

**Comment by pedanticdev** [comment]
Kickstarting the marketing release process via https://github.com/eclipse/microprofile-marketing/issues/949

**Comment by rstjames** [comment]
done
